#ifndef THEMES_RESOURCE_H
#define THEMES_RESOURCE_H

// Идентификаторы для темы square_blue
#define IDB_SQUARE_BLUE_0     101
#define IDB_SQUARE_BLUE_1     102
#define IDB_SQUARE_BLUE_2     103
#define IDB_SQUARE_BLUE_3     104
#define IDB_SQUARE_BLUE_4     105
#define IDB_SQUARE_BLUE_5     106
#define IDB_SQUARE_BLUE_6     107
#define IDB_SQUARE_BLUE_7     108
#define IDB_SQUARE_BLUE_8     109
#define IDB_SQUARE_BLUE_9     110
#define IDB_SQUARE_BLUE_POINT 111
#define IDB_SQUARE_BLUE_PLUS  112
#define IDB_SQUARE_BLUE_MINUS 113
#define IDB_SQUARE_BLUE_ASTER 114
#define IDB_SQUARE_BLUE_SLASH 115
#define IDB_SQUARE_BLUE_BSP   116
#define IDB_SQUARE_BLUE_CLR   117
#define IDB_SQUARE_BLUE_EQUAL 118

// Идентификаторы для темы metal_mistral
#define IDB_METAL_MISTRAL_0     201
#define IDB_METAL_MISTRAL_1     202
#define IDB_METAL_MISTRAL_2     203
#define IDB_METAL_MISTRAL_3     204
#define IDB_METAL_MISTRAL_4     205
#define IDB_METAL_MISTRAL_5     206
#define IDB_METAL_MISTRAL_6     207
#define IDB_METAL_MISTRAL_7     208
#define IDB_METAL_MISTRAL_8     209
#define IDB_METAL_MISTRAL_9     210
#define IDB_METAL_MISTRAL_POINT 211
#define IDB_METAL_MISTRAL_PLUS  212
#define IDB_METAL_MISTRAL_MINUS 213
#define IDB_METAL_MISTRAL_ASTER 214
#define IDB_METAL_MISTRAL_SLASH 215
#define IDB_METAL_MISTRAL_BSP   216
#define IDB_METAL_MISTRAL_CLR   217
#define IDB_METAL_MISTRAL_EQUAL 218

#endif // THEMES_RESOURCE_H